### ISSUE TITLE
Data link appears to be dead

### ISSUE THREAD

**Issue by vadim0x60** [jackbergus/DISeASE#1]
Interesting project! Unfortunately, I failed to get the data using [this link](http://jackbergus.alwaysdata.net/disease/)

**Comment by jackbergus** [comment]
Hello, and thanks for your interest. I know, I had some issues with the old
server. I hope to upload the correct configuration within one week.

In the worst case scenario, I will provide you the raw data that allowed to
generate the binary files, and I will add this info in the project's
documentation.

Il lun 25 giu 2018, 07:22 Vadim Liventsev <notifications@github.com> ha
scritto:

**Comment by jackbergus** [comment]
Hello, sorry for the long reply,
I was able to restore the file from my backup.
Please tell me if this works, so that I will update the read me with this link. 

https://drive.google.com/open?id=0B3tBL-tX2EdQcVlzZHd6cHNXalU
